language: ruby
rvm: 2.2.3
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq postgresql-server-dev-9.3
deploy:
  provider: heroku
  api_key:
    secure: SYv+bM6yPoTI84k8ngXS5tWnIzU7rrkFCYEA5SvuwsOAgZ55Xpwcu+0IQRD/rzF6e0TMp2sroTmrKpgHiA4Ifm/lKSKVlcD+AbpjkY6JQM1idAVYMlnIe1DYfjTHK7kyuUVdQDp1I3CmgzpKc2clula3FzOvUL2vGKeifKAn7cFHkrarG7f80lkHtCGfkXxb+l4FOiRz1gBKfquo2wT+gIotpkE0lvTNeszQBdPoC/kuueom6HE48OwLyZCV9OOAackY0kCeogBzng3DskjRjgHrOM278F8zq73ctrLXAK27kgfvhBqO99XMap1mVfq/OwdI3qG/JbUZZVSAxWHmVctAXraMCm3dxbx55QjD41zpQahTvR9xh/m53QpKgf2N7rPlG4wAWckvtSUBk+kBE2IPEEcmbnZ+FukCc9uOQ9IZ1Fq5UO4IBjOIDgaaBq09JOmQrWSjiC8jJ9s0RZehGlKEBJ7YakiRUhjTwSe1AKtq+jGDqpNeZFjFXTS4KKDgcwqZUTTVDKQxMcEVk18nDeNlyb+oXrQQJriuLB5d8bQxvR9+Wlubx/jSpDHhP9DZteXcbyY3yjtUK8J3usv40RdbEluowKab03PkhYPfWFrKXi2/Bg7et9MYYnhstH3ZDTuJi9t5ovyLBEZGNifbNxiilpHFWfWpruBiYW21dr8=
  app: taigircalculatorservicesoap
  on:
    repo: hdushan/taigirCalculatorServiceSOAP
notifications:
  email:
    recipients:
    - hansrd_98@yahoo.com
