language: ruby
rvm: 2.2.3
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq postgresql-server-dev-9.3
deploy:
  provider: heroku
  app: taigircalculatorservicesoap
  on:
    repo: hdushan/taigircalculatorservicesoap
  api_key:
    secure: ZIyeLulInB6ZfPmiykxgOg6XoUXyGFvKsAebbWn4hwS9H5pFbVjjXueeW1/lsgSMCSZUsf7z40aD1uDwKpHqX5mUnEgiR4LZPnAV45StlEFUoQMXOOTcRgN63Xpkjsx3ChoGMpbNT7KfPfnmnHRKzg+nx9nlUHKut0N9fniJ9LgqnjBZCgYBgbFQkLkqQ4M8k642uPKoFMsSosfs4wDQBZ4RCkgDrCslLALjkdE1voyKqy+RRBZG4QaKRGm12yEUxnGUrDw8KCiV69hXTE7fgCytSOqXjg8kHCviMUi2hoGQ29aIwhBzorP3cnQscXV3aiW1bI1GXnbTQ/xndgeYdm9Ac/Vdyhc+1A1M5qerP3DM5kgGTi58Q/r8PjTFD03lD0ZiWQ//jpUfGrEL35tXnZCEfSAwXL6zSeazenyrk6WD3wV+AP1ODL3c+BPlEUJHiRw3m2VhJeUmA94Bc7dlgo/X9/ztlyLNJA14hGlm2xV0BZWxU5NCA1eefqh9BO2Jbel6I0BDsPTGPHxzDHq4LrW7/VHRbMJmvIZO2vtM4W7pIdGAUAjxHhlB5Xm+MbFFH25ZLVilaIK8IX3CsBY/74qn10s0TlXOO0DTp1hySn/bY0I/3NmLS7ORe+lWdsgnDg1rff45zJBeSZDIDZsUKejseT6BfK+PCkQBPm/hOwo=
notifications:
  email:
    recipients:
    - hansrd_98@yahoo.com
